version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: library_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: library_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: library_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo_admin:password@mongo:27017/?authSource=admin
      - REDIS_URL=redis://redis:6379

volumes:
  mongo_data: